### PR TITLE
Livesplit integration

### PR DESCRIPTION
**Pull request by Avasam**
This extracts @KaDiWa4 's work from PR #50 to implement LiveSplit integration.
This feature works using @KaDiWa4 's [AutoSplit Integration](https://github.com/KaDiWa4/LiveSplit.AutoSplitIntegration) LiveSplit component.

Other than some IDE configurations I've added, all changes are directly related to this one feature. There isn't even automated linting fixes, which, if I do, will be in a different PR.

### CODE REVIEW

**Comment by Avasam** [comment]
There's just one issue. `about.py` clearly states that it's autogenerated code. But I'd like if there was a single source of truth for the version number.
Where and how is `about.py` generated exactly?

**Comment by KaDiWa4** [comment]
I think `about.py` is generated with PyQt from `res/about.ui`

**Comment by Avasam** [comment]
Version number now has a single source of truth in a location that won't get overridden by regenerating code.
Ready for review.

**Comment by Avasam** [comment]
In the mean time, I figured out a much better way to "kill" from dev console. And made the LiveSplit Exit more graceful.

**Comment by Avasam** [comment]
I don't remember whom I discussed this with, but we should be able to communicate with LiveSplit Server. Dropping dependency to [KaDiWa4/LiveSplit.AutoSplitIntegration](https://github.com/KaDiWa4/LiveSplit.AutoSplitIntegration) (a LiveSplit component could still be useful just to automatically start/kill LiveSplit, but would be optional)

**Comment by Avasam** [comment]
After looking more into it. Using the livesplit server is a bad idea. We can't listen to livesplit events (only send commands) and teh server has to be manually started by the user everytime. So this is still the best solution, unless we decide to package AutoSplit itself as a LiveSplit component (which could  also benefit from autoupdates and UI cleanup)

**Pull request merged**
