### PR TITLE
Merge Avasam-Complete to Master

### LINKED ISSUE #8: Numpad number key with numlock on as split hotkey does not split
For example: setting the Start / Split key to numpad0 will set it to 0 instead. When a match occurs, it will hit 0 instead of numpad0. The current workaround for this is to turn numlock off when setting your Start / Split hotkey for both AutoSplit and your preferred speedrun timer.

### LINKED ISSUE #25: Numlock-on keys are linked to numlock-off keys when using them as hotkeys
I noticed that the tool switches threw Split Images when using the Arrow up and Arrow down Key which is unpractical for playing games that use the Arrow Keys to move it would be good if there would be an option to maybe change these Shortcuts

### LINKED ISSUE #30: Splitting when holding shift
I've read that it was a known issue that holding shift, ctrl or alt prevent LiveSplit & WSplit from registering the splitkey correctly.

However, my speedgame implies having to hold shift at some point where a split will occur.

Which is why I'm asking, do you think this issue is likely to get a fix someday? Or is it an issue related to LiveSplit limitations?

If it's actually possible I could help doing so

### LINKED ISSUE #32: Autosplit launches without saved settings when launched via Windows search
On Windows 10, when I open the program by pressing the Windows key and typing "autosplit", then selecting it to run, it opens without any of its saved settings. 
image

I've checked that this is not a different instance of the executable. When I navigate to the exe file via Windows explorer and double click it, it opens with its saved settings as expected.
image

### LINKED ISSUE #52: Using L2 Norm and a Masked image with complete transparency error's out
calculating the error in L2 Norm gives an error of 0 when using a masked image with complete transparency which, when returning 1 - (error / max_error) in this function throws a ZeroDivisionError and AutoSplit won't reset properly after throwing the error. I'm honestly going to ignore this for now because I don't see a situation where comparing an image with complete transparency would be useful, and you can still use the other comparison methods if it's really needed.

### LINKED ISSUE #56: LiveSplit won't detect hotkey activation if not focused
Testing it in Dying Light, if the game is focused when Auto Split activates a split, LiveSplit does not accept it as input. Global Hot Keys is enabled in LiveSplit and the input works fine when pressed physically it just won't receive Auto Split's input unless it is focused. (I have tried multiple different hot keys)

### LINKED ISSUE #62: Invalid file name
Screenshot 2021-05-05 222149
I don't know why this happens, can anyone help me?

### LINKED ISSUE #63: Upgrade to PyQT6
PyQT4 is discontinued and does not support Python 3.8+

### PR DESCRIPTION
**Pull request by Toufool**
Bugs:
Closes #8 
Closes #25  
Closes #30  
Closes #32 
Closes #52 
Closes #56 
Closes #62 
Closes #63

PR's:
Closes #79
Closes #72
Closes #71
Closes #66
Closes #65

### CODE REVIEW

**Comment by Toufool** [comment]
This should be ready to merge to master. Going to wait until @Avasam confirms that we're good to go here. Also going to wait until I can make the release at the same time.

**Comment by Avasam** [comment]
Code lgtm. Check discord for missing changelog items.

**Comment by Avasam** [comment]
Fixes Avasam/Auto-Split/issues/11

**Comment by KaDiWa4** [comment]
Yay

**Pull request merged**
