### PR TITLE
check before PrintWindow

### LINKED ISSUE #74: 1.5.1 max fps performance issues
for what would normally be upwards of Max FPS 1000 for a small capture region, 1.5.1 is only getting like 30. need to look into this more

### PR DESCRIPTION
**Pull request by Avasam**
Fixes #74
The logic goes as follows:
- If we already know whether a window needs PrintWindow to be called, no need to check
- In case we don't know yet (the check is only done once per new window). Check if the rendered image if fully black;
  - if so, PrintWindow needs to be called, and the image is obtained a second time
  - if not, just use the image we already obtained as it's perfectly valid

### CODE REVIEW

**Comment by Avasam** [comment]
As a general comment. Doing an entire application optimization pass eventually might be a good idea for PrintWindow.
Until now it would've been premature optimization with hundreds of frames per second, but on fullscreen Hardware accelerated windows I hardly get 60FPS on a fairly decent computer.
Better it working slow than not at all though 😄

**Comment by Toufool** [comment]
@Avasam If you can remove this line (it was preventing me from running AutoSplit.py) I can merge this in to Master.  https://github.com/Avasam/Auto-Split/blob/5a014131f9e46b6d36b99b68fde384470e20de11/src/AutoSplit.py#L5

**Comment by Toufool** [comment]
Oh yea you can go ahead and change version to 1.5.2 as well, going to release this one so that w10 users dont have to suffer the performance drop

**Comment by Toufool** [comment]
Hold on this actually. Tyron18 was getting a static image in Windows11. testing with him

**Pull request merged**
